apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: myapp
    image: sstechnosolutions/myapp:v0
    volumeMounts:
    - name: myapp-storage
      mountPath: /home/ec2-user
  volumes:
  - name: myapp-storage
    emptyDir: {}
