apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
