apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-ebs-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
