apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myapp
      image: sstechnosolutions/myapp:v0
      volumeMounts:
      - mountPath: "/temp"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: demo-ebs
