apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: myapp
      image: sstechnosolutions/myapp:v0
      # command: ["/bin/bah", "-c", "env"]
      # command: ["echo", "${dev_server_ip}", "${dev_server_password}", "${dev_server_username}"]
      env:
        - name: DEV_SERVER_IP
          valueFrom:
            configMapKeyRef:
              name: dev-server
              key: dev_server_ip
        - name: DEV_SERVER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: dev-server
              key: dev_server_username
        - name: DEV_SERVER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: dev-server
              key: dev_server_password
      volumeMounts:
      - name: dev-mount
        mountPath: "/etc/dev-mount"
        readOnly: true
  volumes:
  - name: dev-mount
    configMap:
      name: dev-server
