apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: sstechnosolutions/myapp:v0
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-secret2
            key: db_username
            optional: false
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret2
            key: db_passwd
            optional: false
  restartPolicy: Never
