apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: sstechnosolutions/myapp:v0
    volumeMounts:
    - name: secrets-demo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: secrets-demo
    secret:
      secretName: my-secret2
      optional: false # default setting; "mysecret" must exist
